services:
  # Génération des certificats
  cert-generator:
    build:
      context: .
      dockerfile: Dockerfile.cert-generator
    environment:
      - CERT_OWNER=${CERT_OWNER}
      - CERT_DOMAIN=${CERT_DOMAIN}
    volumes:
      - certs:/certs
    restart: "no"
    networks:
      - proxy-network

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf
      - certs:/etc/nginx/certs
    depends_on:
      - cert-generator
      - front
      - back
      - static
    networks:
      - proxy-network

  front:
    image: victorbartolomeo/canicampusconnect-view:0.0.9
    expose:
      - "80"
    networks:
      - proxy-network

  back:
    image: victorbartolomeo/canicampusconnect-api:0.0.9
    expose:
      - "8080"
    depends_on:
      - db
    volumes:
      - ${PRIVATE_UPLOAD_FOLDER}:/uploads
    env_file:
      - .env.production
    networks:
      - proxy-network
      - backend-network

  db:
    image: mysql:8.0.43
    expose:
      - "3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - data:/var/lib/mysql
    networks:
      - backend-network

  static:
    image: nginx:latest
    expose:
      - "80"
    volumes:
      - ${PRIVATE_UPLOAD_FOLDER}:/usr/share/nginx/html/images
      - ./nginx-static.conf:/etc/nginx/conf.d/default.conf
    environment:
      - PRIVATE_UPLOAD_FOLDER=${PRIVATE_UPLOAD_FOLDER}
    networks:
      - proxy-network

volumes:
  data:
  certs:

networks:
  proxy-network:
  backend-network: